spring:
  application:
    name: profile
  main:
    allow-bean-definition-overriding: true
  profiles:
    active:
      - dev
server:
  port: 8202
frontend-url: http://apps.local
security:
  disable-csrf: true

############## elastic search configruation ####################
elasticsearch:
  host: localhost
  port: 9200
  scheme: http
      
---
spring:
  profiles: default
cloud:
  aws:
    region:
      static: <region> E.g  ap-south-1, us-east-1
    credentials:
      access-key: <ACCESS KEY>
      secret-key: <SECRET KEY>
    s3:
      bucket: <BUCKET NAME>
    endpoint:
      url: https://s3.${cloud.aws.region.static}.amazonaws.com/${cloud.aws.s3.bucket}

---
spring:
  profiles: dev
localstack:
  enabled: true
  s3:
    enabled: true
cloud:
  aws:
    region:
      static: us-east-1
    credentials:
      access-key: dummy
      secret-key: dummy
    s3:
      bucket: test-bucket
    endpoint:
      url: http://localstack:4572/${cloud.aws.s3.bucket}
